hepsi:derle bagla calistir

derle:
	g++ -I ./include -o ./lib/main.o -c ./src/main.cpp
	g++ -I ./include -o ./lib/Dugum.o -c ./src/Dugum.cpp
	g++ -I ./include -o ./lib/BagliListe.o -c ./src/BagliListe.cpp
bagla:
	g++ -I ./include ./lib/main.o ./lib/Dugum.o ./lib/BagliListe.o -o ./bin/Uygulama
calistir:
	./bin/Uygulama